# Generated by Django 6.0.6 on 2026-06-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_user_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('visa', 'بطاقة عالمية (Visa / MasterCard)'), ('ccp', 'البطاقة الذهبية (CCP)'), ('cod', 'الدفع عند الاستلام')], default='visa', max_length=50, verbose_name='طريقة الدفع'),
        ),
    ]
