# Generated by Django 6.0.6 on 2026-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة / البلدية'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم الكامل'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الولاية'),
        ),
    ]
