"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""
import dj_database_url
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-&e0e&bcdybm_@*o@&x*&2ycmww=x%=fxhw4(#n&uqg#a*(i2=+')

# SECURITY WARNING: don't run with debug turned on in production!
# سيتحول تلقائياً إلى False على سيرفر Render لحماية موقعك
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# إضافة رابط Render ليعمل الموقع حياً بشكل سليم
ALLOWED_HOSTS = ['*', 'mystore-9kma.onrender.com']

# الحماية الموثوقة لروابط ngrok و Render لعدم حدوث خطأ 403 CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
    'https://*.ngrok-free.app',
    'https://mystore-9kma.onrender.com',
]


# Application definition

INSTALLED_APPS = [
    'cloudinary_storage',  # يجب أن تكون فوق staticfiles
    'cloudinary',
    'store',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- الإضافة السحرية لإصلاح التصميم
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # المسؤول عن تغيير وفهم لغات المتصفح والمستخدم
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'store', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # هذا السطر يجعله يستخدم sqlite3 محلياً، ويستخدم الرابط السحابي عند الرفع
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization (الترجمة واللغات)
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ar'  # اللغة الافتراضية للموقع

TIME_ZONE = 'Africa/Algiers'

USE_I18N = True

USE_TZ = True

# اللغات المتاحة في المتجر للاختيار بينها
LANGUAGES = [
    ('ar', 'Arabic'),
    ('en', 'English'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Media Files (توجيه صور المنتجات المرفوعة إلى التخزين السحابي Cloudinary)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# إعدادات مفاتيح الربط السحابية لـ Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}


# Authentication Redirects (توجيهات الحسابات)

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Stripe Keys (مفاتيح بوابة الدفع سترايب - معطلة بناءً على رغبتك)

STRIPE_PUBLIC_KEY = 'pk_test_51TmWq8LMyx04TkRfznukmJhXxMfC5EIUS1d1yg0xfh3qKMxVWj87Zzj0w0KlsK0rjH6fO6j9TrtjjsxH0GDB0xaN00Vi0ayphi'


# ربط الإعدادات المحلية السرية إن وجدت
try:
    from local_settings import *
except ImportError:
    pass